export const baseUrls = [
    "https://kraken.squid.wtf",
    "https://triton.squid.wtf",
    "https://zeus.squid.wtf",
    "https://aether.squid.wtf",
    "https://phoenix.squid.wtf",
    "https://shiva.squid.wtf",
    "https://chaos.squid.wtf",
    "https://tidal-api-2.binimum.org",
    "https://jakarta.monochrome.tf",
    "https://california.monochrome.tf",
    "https://london.monochrome.tf",
    "https://hund.qqdl.site",
    "https://katze.qqdl.site",
    "https://maus.qqdl.site",
    "https://vogel.qqdl.site",
    "https://wolf.qqdl.site",
    "https://hifi.prigoana.com",
    "https://singapore.monochrome.tf",
    "https://ohio.monochrome.tf",
    "https://oregon.monochrome.tf",
    "https://virginia.monochrome.tf",
    "https://frankfurt.monochrome.tf",
    "https://tokyo.monochrome.tf",
  ];
  